/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convert;

import ChatJadro.NGram;

/**
 *
 * @author pawel
 */
public class StatystykiFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatystykiFrame
     */
    public StatystykiFrame() {
        initComponents();
    }

    public void odswiezNajczestsze(Statystyki stat) {
        NGram[] najczestsze = new NGram[10];

        for (int i = 0; i < 10; i++) {
            najczestsze[i] = stat.getNGram(i);
            if (najczestsze[i] == null) {
                break;
            }
            
        }try{
        nGram1.setText(najczestsze[0].getNGram());
        nGram2.setText(najczestsze[1].getNGram());
        nGram3.setText(najczestsze[2].getNGram());
        nGram4.setText(najczestsze[3].getNGram());
        nGram5.setText(najczestsze[4].getNGram());
        }
        catch(NullPointerException e){
            
        }
        int wszystkieWystapienia = 0;
        for( int i = 0; i < 5; i++)
            wszystkieWystapienia += najczestsze[i].getSufiksWyst();
        nGram1Bar.setValue(100 *najczestsze[0].getSufiksWyst()/wszystkieWystapienia);
        nGram2Bar.setValue(100 *najczestsze[1].getSufiksWyst()/wszystkieWystapienia);
        nGram3Bar.setValue(100 *najczestsze[2].getSufiksWyst()/wszystkieWystapienia);
        nGram4Bar.setValue(100 *najczestsze[3].getSufiksWyst()/wszystkieWystapienia);
        nGram5Bar.setValue(100 *najczestsze[4].getSufiksWyst()/wszystkieWystapienia);
        
        nGram1Bar.setString("" + najczestsze[0].getSufiksWyst());
        nGram2Bar.setString("" + najczestsze[1].getSufiksWyst());
        nGram3Bar.setString("" + najczestsze[2].getSufiksWyst());
        nGram4Bar.setString("" + najczestsze[3].getSufiksWyst());
        nGram5Bar.setString("" + najczestsze[4].getSufiksWyst());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        nGram1Bar = new javax.swing.JProgressBar();
        nGram4Bar = new javax.swing.JProgressBar();
        nGram5Bar = new javax.swing.JProgressBar();
        nGram2Bar = new javax.swing.JProgressBar();
        nGram3Bar = new javax.swing.JProgressBar();
        nGram1 = new javax.swing.JLabel();
        nGram2 = new javax.swing.JLabel();
        nGram3 = new javax.swing.JLabel();
        nGram4 = new javax.swing.JLabel();
        nGram5 = new javax.swing.JLabel();
        zamknijBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1050, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Najczęściej występujące n-gramy", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.GridBagLayout());

        nGram1Bar.setBackground(new java.awt.Color(9, 5, 1));
        nGram1Bar.setToolTipText("");
        nGram1Bar.setValue(50);
        nGram1Bar.setName(""); // NOI18N
        nGram1Bar.setString("210");
        nGram1Bar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 216, 0, 6);
        jPanel1.add(nGram1Bar, gridBagConstraints);

        nGram4Bar.setValue(7);
        nGram4Bar.setString("31");
        nGram4Bar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 216, 0, 6);
        jPanel1.add(nGram4Bar, gridBagConstraints);

        nGram5Bar.setValue(3);
        nGram5Bar.setString("7");
        nGram5Bar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 216, 6, 6);
        jPanel1.add(nGram5Bar, gridBagConstraints);

        nGram2Bar.setValue(25);
        nGram2Bar.setString("115");
        nGram2Bar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 216, 0, 6);
        jPanel1.add(nGram2Bar, gridBagConstraints);

        nGram3Bar.setValue(10);
        nGram3Bar.setString("60");
        nGram3Bar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 383;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 216, 0, 6);
        jPanel1.add(nGram3Bar, gridBagConstraints);

        nGram1.setText("ngram #1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(100, 18, 0, 0);
        jPanel1.add(nGram1, gridBagConstraints);

        nGram2.setText("ngram #2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 18, 0, 0);
        jPanel1.add(nGram2, gridBagConstraints);

        nGram3.setText("ngram #3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 18, 0, 0);
        jPanel1.add(nGram3, gridBagConstraints);

        nGram4.setText("ngram #4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 18, 0, 0);
        jPanel1.add(nGram4, gridBagConstraints);

        nGram5.setText("ngram #5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 18, 6, 0);
        jPanel1.add(nGram5, gridBagConstraints);

        zamknijBut.setText("Zamknij");
        zamknijBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zamknijBut)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zamknijBut)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zamknijButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijButActionPerformed
        this.dispose();
    }//GEN-LAST:event_zamknijButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatystykiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatystykiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatystykiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatystykiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatystykiFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JLabel[] ngramy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nGram1;
    private javax.swing.JProgressBar nGram1Bar;
    private javax.swing.JLabel nGram2;
    private javax.swing.JProgressBar nGram2Bar;
    private javax.swing.JLabel nGram3;
    private javax.swing.JProgressBar nGram3Bar;
    private javax.swing.JLabel nGram4;
    private javax.swing.JProgressBar nGram4Bar;
    private javax.swing.JLabel nGram5;
    private javax.swing.JProgressBar nGram5Bar;
    private javax.swing.JButton zamknijBut;
    // End of variables declaration//GEN-END:variables
}
