/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convert;

import java.util.prefs.Preferences;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author pawel
 */
public class UstawieniaFrame extends javax.swing.JFrame {

    private static int staryRzad;
    private static int nowyRzad;
    private static Preferences preferencje;
    
    public UstawieniaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        plikWejsciowy = new javax.swing.JPanel();
        wyborPliku = new javax.swing.JFileChooser();
        rzadNGramow = new javax.swing.JPanel();
        wyborRzeduNGramow = new javax.swing.JSpinner();
        zapiszBut = new javax.swing.JButton();
        anulujBut = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        plikWejsciowy.setBorder(javax.swing.BorderFactory.createTitledBorder("Plik wejściowy"));

        wyborPliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyborPlikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plikWejsciowyLayout = new javax.swing.GroupLayout(plikWejsciowy);
        plikWejsciowy.setLayout(plikWejsciowyLayout);
        plikWejsciowyLayout.setHorizontalGroup(
            plikWejsciowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plikWejsciowyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wyborPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plikWejsciowyLayout.setVerticalGroup(
            plikWejsciowyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plikWejsciowyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wyborPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rzadNGramow.setBorder(javax.swing.BorderFactory.createTitledBorder("Rząd n-gramów"));

        wyborRzeduNGramow.setModel(new javax.swing.SpinnerNumberModel(3, 1, 20, 1));
        wyborRzeduNGramow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        wyborRzeduNGramow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wyborRzeduNGramowStateChanged(evt);
            }
        });

        javax.swing.GroupLayout rzadNGramowLayout = new javax.swing.GroupLayout(rzadNGramow);
        rzadNGramow.setLayout(rzadNGramowLayout);
        rzadNGramowLayout.setHorizontalGroup(
            rzadNGramowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rzadNGramowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wyborRzeduNGramow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        rzadNGramowLayout.setVerticalGroup(
            rzadNGramowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rzadNGramowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wyborRzeduNGramow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        zapiszBut.setText("Zapisz");
        zapiszBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButActionPerformed(evt);
            }
        });

        anulujBut.setText("Anuluj");
        anulujBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anulujBut)
                        .addGap(18, 18, 18)
                        .addComponent(zapiszBut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plikWejsciowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rzadNGramow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(plikWejsciowy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rzadNGramow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zapiszBut)
                    .addComponent(anulujBut))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anulujButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButActionPerformed
    this.dispose();
    }//GEN-LAST:event_anulujButActionPerformed

    private void wyborPlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyborPlikuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wyborPlikuActionPerformed

    private void wyborRzeduNGramowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wyborRzeduNGramowStateChanged
//   wyborRzeduNGramow.getEditor().;
    }//GEN-LAST:event_wyborRzeduNGramowStateChanged

    private void zapiszButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButActionPerformed
        JTextField pole = getTextField(wyborRzeduNGramow);
        System.out.println("zmiana " + pole.getText());
        UstawieniaFrame.nowyRzad = Integer.parseInt(pole.getText());
        if(staryRzad != nowyRzad ){ //zmideniono rzad n-gramow
            preferencje.putInt("rzad", nowyRzad );
        }
        this.dispose();
    }//GEN-LAST:event_zapiszButActionPerformed

      private JFormattedTextField getTextField(JSpinner spinner) {
        JComponent editor = spinner.getEditor(); 
            return ((JSpinner.DefaultEditor)editor).getTextField();
    }

       public void inicujPreferencje(int rzad, Preferences preferencje){
       UstawieniaFrame.staryRzad = rzad;
       UstawieniaFrame.preferencje = preferencje;
       JTextField pole = getTextField(wyborRzeduNGramow);
       pole.setText(Integer.toString(rzad));
    }
    
       public static int getNowyRzad() {
        return nowyRzad;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UstawieniaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UstawieniaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UstawieniaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UstawieniaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UstawieniaFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujBut;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel plikWejsciowy;
    private javax.swing.JPanel rzadNGramow;
    private javax.swing.JFileChooser wyborPliku;
    private javax.swing.JSpinner wyborRzeduNGramow;
    private javax.swing.JButton zapiszBut;
    // End of variables declaration//GEN-END:variables
}
